### ISSUE TITLE
拷贝引擎到SD 卡发生错误

### ISSUE THREAD

**Issue by lxb-symbol** [shuguoli68/LiSeetaFace2#2]
SeetaUtil.copyAssetsToDst(mContext, ROOT_ASSETS, ROOT_CACHE);  发生异常，华为mate9  系统9.0 版本报错。

 java.io.FileNotFoundException: seetaface
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at android.content.res.AssetManager.nativeOpenAsset(Native Method)
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:865)
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:842)
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at com.seeta.sdk.util.SeetaUtil.copyAssetsToDst(SeetaUtil.java:37)
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at com.seeta.sdk.util.SeetaHelper.copyAts(SeetaHelper.java:79)
2020-03-22 08:58:23.477 16240-16517/com.example.seetaface2demo W/System.err:     at com.example.seetaface2demo.MainActivity$initData$1.run(MainActivity.kt:70)
2020-03-22 08:58:23.478 16240-16517/com.example.seetaface2demo W/System.err:     at java.lang.Thread.run(Thread.java:784)

**Comment by lxb-symbol** [comment]
不好意思，我没拷贝模型文件
